apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
  ports:
  - protocol: TCP
    port: 80           # Service port
    targetPort: 8080    # Port on the container
    nodePort: 30080     # Optional: specify the NodePort (choose from the allowed range)
  type: NodePort        # Set type to NodePort
