apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev-ns

nameSuffix: -dev

resources:
- ../../base
- dev-namespace.yaml

# Strategic Merge Patch
patches:
- path: deployment-dev.yaml
- path: service-dev.yaml

images:
- name: nginx
  newTag: alpine-slim

configMapGenerator:
- behavior: replace
  files:
  - index.html
  name: nginx-default-page-config

labels:
- includeSelectors: true
  pairs:
    environment: Development
