apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-ns

nameSuffix: -prod

resources:
- ../../base
- prod-namespace.yaml

# Strategic Merge Patch
patches:
- path: deployment-prod.yaml

configMapGenerator:
- behavior: replace
  files:
  - index.html
  name: nginx-default-page-config

labels:
- includeSelectors: true
  pairs:
    environment: Production 