apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-demo
  labels:
    app: cm-demo 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cm-demo 
  template:
    metadata:
      labels:
        app: cm-demo 
    spec:
      containers:
        - name: app
          image: nimendra/cmdemo:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          resources:
           requests:
            cpu: "100m"
            memory: "128Mi"
           limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: config-volume
          configMap:
            name: config

---
apiVersion: v1
kind: Service
metadata:
  name: cm-demo 
spec:
  selector:
    app: cm-demo  
  ports:
    - port: 80
      targetPort: 8080