apiVersion: apps/v1
kind: Deployment
metadata:
  name: cm-demo
  labels:
    app: cm-demo
  annotations:
    reloader.stakater.com/auto: "true" 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cm-demo 
  template:
    metadata:
      labels:
        app: cm-demo 
    spec:
      containers:
        - name: app
          image: nimendra/cmdemo:2.0.2
          imagePullPolicy: IfNotPresent #<-- to use locally loaded image
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: config-volume
              mountPath: /config
              readOnly: true
          resources:
           requests:
            cpu: "100m"
            memory: "128Mi"
           limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: USER
              valueFrom:
                secretKeyRef:
                  name: kube-secret
                  key: USER
            - name: PASS
              valueFrom:
                secretKeyRef:
                  name: kube-secret
                  key: PASS
      volumes:
        - name: config-volume
          configMap:
            name: config

---
apiVersion: v1
kind: Service
metadata:
  name: cm-demo 
spec:
  selector:
    app: cm-demo  
  ports:
    - port: 80
      targetPort: 8080