apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
  ports:
  - protocol: TCP
    port: 80         # Service port
    targetPort: 8080   # Target port in the container
  type: ClusterIP    # Default service type (internal cluster communication)
