apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  labels:
    app: httpbin
spec:
  selector:
    app: httpbin
  ports:
    - protocol: TCP
      port: 80         # Service port
      targetPort: 8080  # Port in the container
  clusterIP: None      # This creates a headless service (no cluster IP)
