apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80             # Service port (Cluster IP)
      targetPort: 8080     # Container port inside the pod
      nodePort: 30080      # Exposed port on each node (must be between 30000-32767)
