apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stg-ns

nameSuffix: -stg

resources:
- ../../base
- stg-namespace.yaml

# Strategic Merge Patch
patches:
- path: deployment-stg.yaml

configMapGenerator:
- behavior: replace
  files:
  - index.html
  name: nginx-default-page-config

labels:
- includeSelectors: true
  pairs:
    environment: Staging 