apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80           # Service port
    targetPort: 80    # Port on the container
    nodePort: 30080 
