services:
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    networks:
      - redis-network

  client:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: go-client
    ports:
      - "8080:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=strongPassword
    networks:
      - redis-network
    depends_on:
      - redis

volumes:
  redis-data:

networks:
  redis-network:
    driver: bridge
