apiVersion: v1
kind: Service
metadata:
  name: env-reader-service
  namespace: default
spec:
  selector:
    app: env-reader
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30080
  type: NodePort
