apiVersion: v1
kind: Service
metadata:
  name: env-reader-service-2
  namespace: default
spec:
  selector:
    app: env-reader-2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 30088
  type: NodePort
